#
# Copyright (c) 2015 Mariusz Zaborski <oshogbo@FreeBSD.org>
#

include make/pre_common.mk
include make/nvlistfiles.mk

CFLAGS+=	-I${LIBNV} -I${LIBNVCONTRIB}

all: ${NVLISTOBJ}

${OBJDIR}/%.o: ${LIBNV}/%.c
	$(CC) -c $(CFLAGS) -o $@ $<

${OBJDIR}/%.o: ${LIBNVCONTRIB}/%.c
	$(CC) -c $(CFLAGS) -o $@ $<
